# Generated by Django 3.0.5 on 2020-06-10 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_auto_20200508_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='subject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=11)),
                ('subject_name', models.CharField(max_length=80)),
                ('total_marks', models.CharField(max_length=3)),
                ('total_credits', models.CharField(max_length=2)),
                ('semester', models.CharField(max_length=1)),
            ],
        ),
        migrations.RemoveField(
            model_name='studentextra',
            name='fee',
        ),
        migrations.AlterField(
            model_name='studentextra',
            name='cl',
            field=models.CharField(choices=[('one', 'one'), ('two', 'two'), ('three', 'three'), ('four', 'four'), ('five', 'five'), ('six', 'six'), ('seven', 'seven'), ('eight', 'eight')], default='one', max_length=10),
        ),
        migrations.AlterField(
            model_name='teacherextra',
            name='salary',
            field=models.PositiveIntegerField(null=True),
        ),
    ]
