# Generated by Django 3.0.5 on 2020-06-10 08:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0015_notice_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='total_marks',
        ),
    ]
