# Generated by Django 3.0.5 on 2020-06-10 08:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0016_remove_subject_total_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subjects',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_code', models.CharField(max_length=11)),
                ('subject_name', models.CharField(max_length=80)),
                ('semester', models.CharField(max_length=2)),
                ('total_credits', models.CharField(max_length=2)),
                ('subject_total_marks', models.CharField(default='120', max_length=2)),
            ],
        ),
        migrations.DeleteModel(
            name='subject',
        ),
    ]
