# Generated by Django 3.0.5 on 2020-06-10 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0018_auto_20200610_0808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='subject_total_marks',
            field=models.CharField(default='120', max_length=3),
        ),
    ]
