# Generated by Django 3.0.5 on 2020-06-10 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0019_auto_20200610_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subject',
            name='subject_total_marks',
        ),
    ]
