# Generated by Django 3.0.5 on 2020-06-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0020_remove_subject_subject_total_marks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_total_marks',
            field=models.CharField(default='120', max_length=3),
        ),
    ]
