# Generated by Django 3.0.5 on 2020-06-10 08:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0021_subject_subject_total_marks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Academics',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll', models.PositiveIntegerField()),
                ('subject_code', models.CharField(max_length=11)),
                ('obtained_marks', models.CharField(default='120', max_length=3)),
                ('obtained_gp', models.CharField(default='120', max_length=1)),
            ],
        ),
    ]
