# Generated by Django 3.0.5 on 2020-06-10 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0022_academics'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='obtained_gp',
            field=models.CharField(max_length=1),
        ),
        migrations.AlterField(
            model_name='academics',
            name='obtained_marks',
            field=models.CharField(default=' ', max_length=3),
        ),
        migrations.AlterField(
            model_name='academics',
            name='roll',
            field=models.CharField(max_length=11),
        ),
    ]
