# Generated by Django 3.0.5 on 2020-06-10 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0023_auto_20200610_0850'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='obtained_gp',
            field=models.CharField(max_length=2),
        ),
    ]
