# Generated by Django 3.0.5 on 2020-06-10 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0024_auto_20200610_0851'),
    ]

    operations = [
        migrations.AlterField(
            model_name='academics',
            name='obtained_marks',
            field=models.CharField(default='', max_length=4),
        ),
    ]
